# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='imagem_post',
            new_name='imagem',
        ),
    ]
