# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('imagem', models.CharField(max_length=255, verbose_name='Imagem do Post')),
                ('video', models.CharField(max_length=255, verbose_name='Video')),
                ('body', models.TextField(verbose_name='Corpo do Post')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de alteração')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostsHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('imagem', models.CharField(max_length=255, verbose_name='Imagem do Post')),
                ('body', models.TextField(verbose_name='Corpo do Post')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de alteração')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
