# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160913_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsblog',
            name='brief_body',
            field=models.TextField(default='Resumo do post do blog.', max_length=200, verbose_name='Resumo do Post'),
        ),
        migrations.AddField(
            model_name='postshome',
            name='brief_body',
            field=models.TextField(default='Resumo do post da novidade.', max_length=200, verbose_name='Resumo da Novidade'),
        ),
    ]
