# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 03:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160920_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsblog',
            name='imagem_vitrine',
            field=models.CharField(default=datetime.datetime(2016, 9, 30, 3, 5, 5, 175643, tzinfo=utc), max_length=255, verbose_name='Imagem vitrine home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postshome',
            name='imagem_vitrine',
            field=models.CharField(default=datetime.datetime(2016, 9, 30, 3, 5, 13, 705656, tzinfo=utc), max_length=255, verbose_name='Imagem vitrine home'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postsblog',
            name='video',
            field=models.CharField(blank=True, max_length=255, verbose_name='Video'),
        ),
    ]
