# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160930_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensSlideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_imagem', models.CharField(max_length=255, verbose_name='Link da imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
            ],
        ),
    ]
