# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imagensslideshow_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_destaque',
            field=models.BooleanField(default=False, verbose_name='Vídeo Destaque'),
        ),
    ]
