# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_imagensslideshow_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='descricao',
            field=models.CharField(default='Descricao do video', max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='imagem_capa',
            field=models.CharField(default='teste', max_length=255, verbose_name='Imagem capa'),
            preserve_default=False,
        ),
    ]
