# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161027_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitrines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_vitrine_blog', models.CharField(max_length=255, verbose_name='Vitrine pagina blog')),
                ('link_vitrine_novidades', models.CharField(max_length=255, verbose_name='Vitrine página novidades')),
                ('link_vitrine_videos', models.CharField(max_length=255, verbose_name='Vitrine página vídeos')),
                ('link_vitrine_about', models.CharField(max_length=255, verbose_name='Vitrine página sobre nós')),
                ('link_vitrine_contato', models.CharField(max_length=255, verbose_name='Vitrine página contato')),
            ],
            options={
                'verbose_name': 'Vitrine do site',
                'verbose_name_plural': 'Vitrines do site',
            },
        ),
    ]
