# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161027_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsblog',
            name='category',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.PostCategories',
                null=True
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='postsblog',
            name='category',
        ),
    ]
