# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161027_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsblog',
            name='category',
        ),
    ]
