# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_postsblog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsblog',
            name='category',
        ),
        migrations.AddField(
            model_name='videos',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.PostCategories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='name',
            field=models.CharField(default='1', max_length=255, verbose_name='Categoria'),
        ),
    ]
