# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161101_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitrines',
            name='titulo_vitrine_about',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página sobre nós'),
        ),
        migrations.AlterField(
            model_name='vitrines',
            name='titulo_vitrine_blog',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página blog'),
        ),
        migrations.AlterField(
            model_name='vitrines',
            name='titulo_vitrine_contato',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página contato'),
        ),
        migrations.AlterField(
            model_name='vitrines',
            name='titulo_vitrine_novidades',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página novidades'),
        ),
        migrations.AlterField(
            model_name='vitrines',
            name='titulo_vitrine_videos',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página vídeos'),
        ),
    ]
