# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161108_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='postshome',
            name='imagem_lateral',
            field=models.CharField(blank=True, max_length=255, verbose_name='Imagem lateral do Post'),
        ),
    ]
