# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170104_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('texto', models.TextField(max_length=400, verbose_name='Depoimento')),
            ],
        ),
    ]
