# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_depoimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrines',
            name='link_vitrine_loja',
            field=models.CharField(default=datetime.datetime(2017, 1, 13, 18, 14, 6, 421696, tzinfo=utc), max_length=255, verbose_name='Vitrine página loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitrines',
            name='link_vitrine_men',
            field=models.CharField(default=datetime.datetime(2017, 1, 13, 18, 14, 17, 936115, tzinfo=utc), max_length=255, verbose_name='Vitrine página linha men'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitrines',
            name='sub_titulo_vitrine_loja',
            field=models.CharField(blank=True, max_length=180, verbose_name='Sub Título vitrine página loja'),
        ),
        migrations.AddField(
            model_name='vitrines',
            name='sub_titulo_vitrine_men',
            field=models.CharField(blank=True, max_length=180, verbose_name='Sub Título vitrine página linha men'),
        ),
        migrations.AddField(
            model_name='vitrines',
            name='titulo_vitrine_loja',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página loja'),
        ),
        migrations.AddField(
            model_name='vitrines',
            name='titulo_vitrine_men',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título vitrine página linha men'),
        ),
    ]
